name = "mumoira"
main = ".open-next/worker.js"
compatibility_date = "2026-04-03"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]
workers_dev = false

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "mumoira"

[triggers]
crons = ["*/15 * * * *"]

[vars]
APP_BASE_URL = "https://mumoira.id.vn"

[[d1_databases]]
binding = "DB"
database_name = "mumoiradb"
database_id = "081ee227-67ba-47c9-96f9-e7c85e1eb687"
migrations_dir = "drizzle"
