// @ts-expect-error: generated by OpenNext during Cloudflare build/deploy
export { default } from "../.open-next/worker";

import type { ExecutionContext } from "@cloudflare/workers-types";
import { runExpireBannersWithRetry, type Env } from "./cron";

type ScheduledController = {
  cron: string;
  scheduledTime: number;
};

export async function scheduled(
  _controller: ScheduledController,
  env: Env,
  ctx: ExecutionContext,
) {
  ctx.waitUntil(runExpireBannersWithRetry(env));
}
